# Generated by Django 3.0.8 on 2020-08-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('on_sale', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='状态')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='描述信息')),
                ('deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('published_at', models.DateField(verbose_name='发布日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
