# Generated by Django 3.0.8 on 2020-08-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200802_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_at', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
