# Generated by Django 3.0.8 on 2020-08-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_comment_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
