# Generated by Django 3.0.8 on 2020-08-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200804_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=20, verbose_name='用户名'),
        ),
    ]
